package org.drakon.drakonchat;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.nio.charset.StandardCharsets;
import java.security.*;
import java.util.*;
import org.json.*;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;

public class MainActivity extends Activity {
    LinearLayout root;
    String email="", role="";
    JSONObject users, chats;
    SharedPreferences prefs;
    int themeIndex=0;
    final int[] BG={Color.rgb(10,4,24),Color.rgb(7,10,27),Color.rgb(5,20,17),Color.rgb(25,10,8)};
    final int[] CARD={Color.rgb(35,12,62),Color.rgb(17,25,55),Color.rgb(12,43,35),Color.rgb(54,22,12)};
    final int[] ACCENT={Color.rgb(181,61,255),Color.rgb(71,126,255),Color.rgb(35,205,145),Color.rgb(235,145,35)};
    final int TXT=Color.rgb(250,247,255), MUTED=Color.rgb(193,181,211), GOLD=Color.rgb(255,205,72), CYAN=Color.rgb(83,207,255);
    final int PICK_AVATAR=7001;

    @Override public void onCreate(Bundle b){
        super.onCreate(b);
        prefs=getSharedPreferences("db",0);
        themeIndex=prefs.getInt("theme",0);
        users=loadObject("users"); chats=loadObject("chats");
        ensureAdmin(); applyBars(); showLogin();
    }
    void applyBars(){getWindow().setStatusBarColor(BG[themeIndex]);getWindow().setNavigationBarColor(BG[themeIndex]);}
    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+0.5f);}
    TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextColor(TXT);t.setTextSize(sp);t.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);t.setPadding(dp(12),dp(8),dp(12),dp(8));return t;}
    EditText input(String hint,boolean pass){EditText e=new EditText(this);e.setHint(hint);e.setHintTextColor(Color.rgb(140,126,160));e.setTextColor(TXT);e.setTextSize(16);e.setSingleLine(true);e.setPadding(dp(15),0,dp(15),0);e.setBackground(round(Color.rgb(25,10,40),dp(14)));if(pass)e.setInputType(0x81);else e.setInputType(0x21);return e;}
    GradientDrawable round(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(radius);g.setStroke(dp(1),Color.argb(90,255,255,255));return g;}
    GradientDrawable border(int color,int stroke){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(18));g.setStroke(dp(1),stroke);return g;}
    GradientDrawable gradient(){return new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{BG[themeIndex],CARD[themeIndex],Color.rgb(Math.min(255,BG[themeIndex]+12),Math.min(255,BG[themeIndex]+6),Math.min(255,BG[themeIndex]+25))});}
    Button btn(String text){Button b=new Button(this);b.setText(text);b.setTextColor(TXT);b.setTextSize(15);b.setAllCaps(false);b.setMinHeight(dp(52));b.setPadding(dp(6),0,dp(6),0);b.setBackground(round(CARD[themeIndex],dp(16)));return b;}
    TextView section(String s){TextView t=tv(s,18);t.setTypeface(null,Typeface.BOLD);t.setTextColor(GOLD);return t;}
    void base(){ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.setBackground(gradient());root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(12),dp(10),dp(12),dp(14));sc.addView(root,new ScrollView.LayoutParams(-1,-1));setContentView(sc);applyBars();}
    void add(View v,int h){root.addView(v,new LinearLayout.LayoutParams(-1,dp(h)));}
    void addWrap(View v){root.addView(v,new LinearLayout.LayoutParams(-1,-2));}
    TextView title(String s){TextView t=tv(s,25);t.setTypeface(null,Typeface.BOLD);t.setTextColor(TXT);return t;}
    void topBar(String name,View.OnClickListener back){LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);Button b=btn("‹");b.setTextSize(30);bar.addView(b,new LinearLayout.LayoutParams(dp(55),dp(54)));bar.addView(title(name),new LinearLayout.LayoutParams(0,dp(54),1));root.addView(bar);b.setOnClickListener(back);}

    void showLogin(){
        base(); add(new Space(this),18);
        ImageView im=new ImageView(this);im.setImageResource(R.drawable.deewan);im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);add(im,140);
        TextView logo=tv("♛ DRAGON CHAT ♛",30);logo.setGravity(Gravity.CENTER);logo.setTypeface(null,Typeface.BOLD);logo.setTextColor(GOLD);add(logo,58);
        TextView sub=tv("عالمك الخاص للدردشة والألعاب والمنافسات",15);sub.setGravity(Gravity.CENTER);add(sub,42);
        EditText e=input("البريد الإلكتروني",false),p=input("كلمة السر",true);add(e,58);add(p,58);
        Button login=btn("دخول إلى الحساب");add(login,60);login.setOnClickListener(v->login(e.getText().toString().trim(),p.getText().toString()));
        Button reg=btn("إنشاء حساب جديد");add(reg,60);reg.setOnClickListener(v->showRegister());
        Button th=btn("🎨 ألوان التطبيق");add(th,55);th.setOnClickListener(v->themeDialog());
        add(tv("المدير الافتراضي: admin@drakon.com",12),34);
    }
    void showRegister(){
        base();topBar("إنشاء حساب جديد",v->showLogin());add(section("أنشئ ملفك داخل Dragon Chat"),52);
        EditText e=input("البريد الإلكتروني",false),p=input("كلمة السر - 6 أحرف على الأقل",true),c=input("تأكيد كلمة السر",true),n=input("اسم العضو",false);add(n,58);add(e,58);add(p,58);add(c,58);
        Button country=btn("🇮🇶  اختيار العلم / البلد");add(country,58);
        final String[] chosen={"🇮🇶","العراق"};country.setOnClickListener(v->countryDialog(chosen,()->country.setText(chosen[0]+"  "+chosen[1])));
        Button b=btn("إنشاء الحساب");add(b,62);b.setOnClickListener(v->{String em=e.getText().toString().trim(),pw=p.getText().toString(),cf=c.getText().toString(),nm=n.getText().toString().trim();if(!em.contains("@")||pw.length()<6||!pw.equals(cf)||nm.isEmpty()){notice("تحقق من الاسم والبريد وكلمة السر.");return;}try{if(users.has(em)){notice("الحساب موجود مسبقاً.");return;}String[]h=hash(pw,null);JSONObject u=new JSONObject();u.put("email",em);u.put("password_salt",h[0]);u.put("password_hash",h[1]);u.put("role","member");u.put("coins",0);u.put("level",1);u.put("active",true);u.put("id",newUserId());u.put("name",nm);u.put("bio","أهلاً بكم في Dragon Chat");u.put("specialIdAllowed",false);u.put("avatar","");u.put("countryFlag",chosen[0]);u.put("countryName",chosen[1]);u.put("online",true);users.put(em,u);save();notice("تم إنشاء الحساب. رقم العضوية: "+u.optString("id"));showLogin();}catch(Exception x){notice("حدث خطأ أثناء إنشاء الحساب.");}});
    }
    void login(String em,String pw){try{if(!users.has(em)){notice("الحساب غير موجود.");return;}JSONObject u=users.getJSONObject(em);if(!u.optBoolean("active",true)){notice("الحساب غير نشط.");return;}if(!verify(pw,u.getString("password_salt"),u.getString("password_hash"))){notice("البريد أو كلمة السر غير صحيحة.");return;}email=em;role=u.optString("role","member");ensureUserFields(u);u.put("online",true);save();showHome();}catch(Exception x){notice("حدث خطأ.");}}

    String levelName(int level){String[]n={"مبتدئ","عضو","عضو نشط","متقدم","محترف","VIP","VIP Plus","نجم","أسطورة","نخبة"};if(level>=1&&level<=n.length)return n[level-1];return level==99?"مدير":"مستوى "+level;}
    View avatar(String em,int size){ImageView im=new ImageView(this);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setClipToOutline(true);GradientDrawable bg=round(ACCENT[themeIndex],dp(size/2));bg.setShape(GradientDrawable.OVAL);im.setBackground(bg);try{String a=users.getJSONObject(em).optString("avatar","");if(!a.isEmpty())im.setImageURI(Uri.parse(a));else im.setImageResource(R.drawable.deewan);}catch(Exception e){im.setImageResource(R.drawable.deewan);}return im;}
    TextView pill(String s){TextView t=tv(s,13);t.setGravity(Gravity.CENTER);t.setTypeface(null,Typeface.BOLD);t.setBackground(round(ACCENT[themeIndex],dp(18)));return t;}

    LinearLayout profileHero(JSONObject u,String em,boolean compact){
        LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(12),dp(12),dp(12),dp(12));card.setBackground(border(CARD[themeIndex],Color.argb(190,190,45,255)));
        LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);
        row.addView(avatar(em,compact?76:105),new LinearLayout.LayoutParams(dp(compact?76:105),dp(compact?76:105)));
        LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL);info.setGravity(Gravity.RIGHT);info.setPadding(dp(12),0,dp(4),0);
        TextView nm=tv((u.optString("role").equals("admin")?"♛ ":"")+u.optString("name","عضو"),compact?20:25);nm.setTypeface(null,Typeface.BOLD);nm.setTextColor(GOLD);info.addView(nm,new LinearLayout.LayoutParams(-1,dp(34)));
        TextView id=tv("ID : "+u.optString("id"),14);id.setTextColor(CYAN);info.addView(id,new LinearLayout.LayoutParams(-1,dp(28)));
        info.addView(tv(u.optString("countryFlag","🇮🇶")+"  "+u.optString("countryName","العراق"),14),new LinearLayout.LayoutParams(-1,dp(28)));
        info.addView(tv("✦ "+levelName(u.optInt("level",1))+"   •   💎 "+u.optInt("coins",0),14),new LinearLayout.LayoutParams(-1,dp(28)));
        row.addView(info,new LinearLayout.LayoutParams(0,compact?80:112,1));card.addView(row);
        if(!compact){TextView bio=tv("♛  "+u.optString("bio","أهلاً بكم في Dragon Chat"),15);bio.setTextColor(TXT);bio.setGravity(Gravity.RIGHT);card.addView(bio,new LinearLayout.LayoutParams(-1,dp(38)));ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(100);pb.setProgress(Math.min(100,u.optInt("level",1)*10));pb.setProgressTintList(android.content.res.ColorStateList.valueOf(ACCENT[themeIndex]));card.addView(pb,new LinearLayout.LayoutParams(-1,dp(12)));LinearLayout st=new LinearLayout(this);st.setPadding(0,dp(7),0,0);TextView a=pill("💎 "+u.optInt("coins",0)+" عملة");TextView b=pill("LV "+u.optInt("level",1));TextView c=pill("♛ "+(u.optString("role").equals("admin")?"مدير":levelName(u.optInt("level",1))));st.addView(a,new LinearLayout.LayoutParams(0,dp(42),1));st.addView(b,new LinearLayout.LayoutParams(0,dp(42),1));st.addView(c,new LinearLayout.LayoutParams(0,dp(42),1));card.addView(st);}return card;
    }

    void showHome(){
        base();
        try{JSONObject u=users.getJSONObject(email);ensureUserFields(u);
            LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);Button settings=btn("⚙");settings.setTextSize(22);head.addView(settings,new LinearLayout.LayoutParams(dp(55),dp(55)));TextView logo=tv("♛ DRAGON CHAT ♛",25);logo.setGravity(Gravity.CENTER);logo.setTextColor(GOLD);logo.setTypeface(null,Typeface.BOLD);head.addView(logo,new LinearLayout.LayoutParams(0,dp(55),1));Button bell=btn("🔔");head.addView(bell,new LinearLayout.LayoutParams(dp(55),dp(55)));root.addView(head);settings.setOnClickListener(v->themeDialog());
            TextView brand=tv("أكثر من مجرد دردشة .. عالمك الخاص",14);brand.setGravity(Gravity.CENTER);add(brand,34);
            root.addView(profileHero(u,email,true),new LinearLayout.LayoutParams(-1,-2));
            LinearLayout actions=new LinearLayout(this);actions.setPadding(0,dp(8),0,dp(5));String[]acts={"♛ ترقية VIP","★ رفع المستوى","♜ رفع المنصب","✦ مميز ID"};for(String a:acts){Button q=btn(a);q.setTextSize(13);actions.addView(q,new LinearLayout.LayoutParams(0,dp(72),1));if(a.contains("VIP"))q.setOnClickListener(v->simple("VIP","ترقية VIP وميزات الحساب الخاصة."));else if(a.contains("المستوى"))q.setOnClickListener(v->simple("المستوى","تطور حسابك من خلال النشاط والمكافآت."));else if(a.contains("المنصب")){if("admin".equals(role))q.setOnClickListener(v->showAdmin());else q.setOnClickListener(v->notice("صلاحية رفع المنصب للمدير فقط."));}else q.setOnClickListener(v->showProfile(email));}addWrap(actions);
            LinearLayout nav=new LinearLayout(this);String[]ns={"🎁 الهدايا","🏆 الأحداث","⚔ المعركة","🎮 الألعاب","👥 الأصدقاء","💬 المجلس"};for(String n:ns){Button q=btn(n);q.setTextSize(12);nav.addView(q,new LinearLayout.LayoutParams(0,dp(68),1));if(n.contains("الأصدقاء"))q.setOnClickListener(v->showFriends());else if(n.contains("المجلس"))q.setOnClickListener(v->showChatList());else if(n.contains("المعركة"))q.setOnClickListener(v->showBattle());else if(n.contains("الألعاب"))q.setOnClickListener(v->showGames());else if(n.contains("الأحداث"))q.setOnClickListener(v->showEvents());else q.setOnClickListener(v->simple("الهدايا","الهدايا والمكافآت اليومية تظهر هنا."));}addWrap(nav);
            LinearLayout banner=new LinearLayout(this);banner.setGravity(Gravity.CENTER);banner.setPadding(dp(8),dp(8),dp(8),dp(8));banner.setBackground(border(Color.rgb(31,8,55),Color.MAGENTA));ImageView bi=new ImageView(this);bi.setImageResource(R.drawable.deewan);bi.setScaleType(ImageView.ScaleType.CENTER_CROP);banner.addView(bi,new LinearLayout.LayoutParams(dp(150),dp(90)));LinearLayout bt=new LinearLayout(this);bt.setOrientation(LinearLayout.VERTICAL);TextView bl=tv("DRAGON CHAT",24);bl.setTextColor(GOLD);bl.setGravity(Gravity.CENTER);bt.addView(bl,new LinearLayout.LayoutParams(-1,dp(42)));bt.addView(tv("عالمك .. لعبك .. أصدقاؤك",13),new LinearLayout.LayoutParams(-1,dp(34)));banner.addView(bt,new LinearLayout.LayoutParams(0,dp(90),1));addWrap(banner);
            LinearLayout lower=new LinearLayout(this);lower.setPadding(0,dp(8),0,dp(8));
            LinearLayout rewards=new LinearLayout(this);rewards.setOrientation(LinearLayout.VERTICAL);rewards.setPadding(dp(10),dp(8),dp(10),dp(8));rewards.setBackground(round(CARD[themeIndex],dp(18)));rewards.addView(section("🎁 المكافآت اليومية"),new LinearLayout.LayoutParams(-1,dp(40)));rewards.addView(tv("سجل الدخول واحصل على مكافآت",13),new LinearLayout.LayoutParams(-1,dp(32)));Button claim=btn("استلام المكافأة  🎁");rewards.addView(claim,new LinearLayout.LayoutParams(-1,dp(50)));claim.setOnClickListener(v->{try{u.put("coins",u.optInt("coins",0)+100);save();notice("تمت إضافة 100 عملة إلى حسابك.");showHome();}catch(Exception e){}});
            LinearLayout online=new LinearLayout(this);online.setOrientation(LinearLayout.VERTICAL);online.setPadding(dp(10),dp(8),dp(10),dp(8));online.setBackground(round(CARD[themeIndex],dp(18)));online.addView(section("🟢 الأعضاء المتصلون"),new LinearLayout.LayoutParams(-1,dp(40)));int count=0;Iterator<String>it=users.keys();while(it.hasNext()&&count<4){String em=it.next();JSONObject x=users.optJSONObject(em);if(x==null||!x.optBoolean("online",true))continue;LinearLayout rr=new LinearLayout(this);rr.setGravity(Gravity.CENTER_VERTICAL);rr.addView(avatar(em,38),new LinearLayout.LayoutParams(dp(38),dp(38)));TextView z=tv(x.optString("name","عضو")+"  •  "+levelName(x.optInt("level",1)),12);rr.addView(z,new LinearLayout.LayoutParams(0,dp(44),1));Button open=btn("›");rr.addView(open,new LinearLayout.LayoutParams(dp(42),dp(44)));open.setOnClickListener(v->showProfile(em));online.addView(rr);count++;}lower.addView(rewards,new LinearLayout.LayoutParams(0,dp(190),1));lower.addView(online,new LinearLayout.LayoutParams(0,dp(190),1));addWrap(lower);
            LinearLayout bottom=new LinearLayout(this);bottom.setPadding(0,dp(5),0,0);String[]bn={"⌂ الرئيسية","💬 المجلس","⚔ المعركة","👥 الأصدقاء","👤 ملف"};for(String n:bn){Button q=btn(n);q.setTextSize(12);bottom.addView(q,new LinearLayout.LayoutParams(0,dp(58),1));if(n.contains("المجلس"))q.setOnClickListener(v->showChatList());else if(n.contains("المعركة"))q.setOnClickListener(v->showBattle());else if(n.contains("الأصدقاء"))q.setOnClickListener(v->showFriends());else if(n.contains("ملف"))q.setOnClickListener(v->showProfile(email));}addWrap(bottom);
        }catch(Exception e){notice("تعذر فتح الصفحة الرئيسية.");}
    }

    void showProfile(String em){
        base();topBar("الملف الشخصي",v->showHome());
        try{JSONObject u=users.getJSONObject(em);ensureUserFields(u);addWrap(profileHero(u,em,false));
            LinearLayout details=new LinearLayout(this);details.setOrientation(LinearLayout.VERTICAL);details.setPadding(dp(12),dp(10),dp(12),dp(10));details.setBackground(round(CARD[themeIndex],dp(18)));
            details.addView(section("معلومات الحساب"),new LinearLayout.LayoutParams(-1,dp(42)));
            details.addView(tv("👤 الاسم: "+u.optString("name","عضو"),14),new LinearLayout.LayoutParams(-1,dp(35)));
            details.addView(tv("🆔 رقم العضوية: "+u.optString("id"),14),new LinearLayout.LayoutParams(-1,dp(35)));
            details.addView(tv("🌍 البلد: "+u.optString("countryFlag","🇮🇶")+"  "+u.optString("countryName","العراق"),14),new LinearLayout.LayoutParams(-1,dp(35)));
            details.addView(tv("🏅 الرتبة: "+(u.optString("role").equals("admin")?"مدير":levelName(u.optInt("level",1))),14),new LinearLayout.LayoutParams(-1,dp(35)));
            if("admin".equals(u.optString("role"))) details.addView(tv("👑 حساب إداري - صلاحيات إدارة الأعضاء",14),new LinearLayout.LayoutParams(-1,dp(38)));
            else details.addView(tv(u.optBoolean("specialIdAllowed",false)?"✦ ID مميز: مسموح من المدير":"✦ ID مميز: غير مفعل",14),new LinearLayout.LayoutParams(-1,dp(38)));
            root.addView(details,new LinearLayout.LayoutParams(-1,-2));
            if(em.equals(email)){Button edit=btn("✏ تعديل الملف والصورة");add(edit,58);edit.setOnClickListener(v->editProfile());Button country=btn("🌍 تغيير العلم / البلد");add(country,58);country.setOnClickListener(v->{String[]c={u.optString("countryFlag","🇮🇶"),u.optString("countryName","العراق")};countryDialog(c,()->{try{u.put("countryFlag",c[0]);u.put("countryName",c[1]);save();showProfile(email);}catch(Exception x){}});});}
            if("admin".equals(role)&&!em.equals(email)){Button chat=btn("💬 مراسلة العضو");add(chat,58);chat.setOnClickListener(v->showChat(em));}
        }catch(Exception e){notice("تعذر فتح الملف.");}
    }
    void editProfile(){try{JSONObject u=users.getJSONObject(email);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText n=input("الاسم",false),bio=input("النبذة",false);n.setText(u.optString("name",""));bio.setText(u.optString("bio",""));box.addView(n,new LinearLayout.LayoutParams(-1,dp(58)));box.addView(bio,new LinearLayout.LayoutParams(-1,dp(58)));Button pick=btn("🖼 اختيار صورة");box.addView(pick,new LinearLayout.LayoutParams(-1,dp(54)));pick.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_AVATAR);});new AlertDialog.Builder(this).setTitle("تعديل الملف").setView(box).setPositiveButton("حفظ",(d,w)->{try{u.put("name",n.getText().toString().trim());u.put("bio",bio.getText().toString().trim());save();showProfile(email);}catch(Exception x){}}).setNegativeButton("إلغاء",null).show();}catch(Exception e){}}
    @Override protected void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==PICK_AVATAR&&c==RESULT_OK&&data!=null&&data.getData()!=null){try{JSONObject u=users.getJSONObject(email);u.put("avatar",data.getData().toString());save();showProfile(email);}catch(Exception ignored){}}}

    void countryDialog(String[] chosen,Runnable done){String[][]c={{"🇮🇶","العراق"},{"🇸🇦","السعودية"},{"🇦🇪","الإمارات"},{"🇰🇼","الكويت"},{"🇶🇦","قطر"},{"🇧🇭","البحرين"},{"🇴🇲","عُمان"},{"🇾🇪","اليمن"},{"🇯🇴","الأردن"},{"🇵🇸","فلسطين"},{"🇱🇧","لبنان"},{"🇸🇾","سوريا"},{"🇪🇬","مصر"},{"🇸🇩","السودان"},{"🇱🇾","ليبيا"},{"🇹🇳","تونس"},{"🇩🇿","الجزائر"},{"🇲🇦","المغرب"},{"🇲🇷","موريتانيا"},{"🇸🇴","الصومال"},{"🇩🇯","جيبوتي"},{"🇰🇲","جزر القمر"}};String[]items=new String[c.length];for(int i=0;i<c.length;i++)items[i]=c[i][0]+"  "+c[i][1];new AlertDialog.Builder(this).setTitle("اختيار علم بلدك").setItems(items,(d,w)->{chosen[0]=c[w][0];chosen[1]=c[w][1];done.run();}).show();}

    void showGames(){base();topBar("الألعاب",v->showHome());add(section("🎮 الألعاب"),48);String[]g={"🎯 تحدي السرعة","🧩 الألغاز","🏆 مسابقة النقاط","🎲 لعبة الحظ المجانية","⚡ تحدي الأصدقاء","🛡 ساحة الأبطال"};for(String s:g){Button b=btn(s+"\nابدأ اللعب");add(b,72);b.setOnClickListener(v->notice("هذه اللعبة واجهتها جاهزة ويمكن ربطها بنظام اللعب لاحقاً."));}}
    void showBattle(){base();topBar("المعركة",v->showHome());add(section("⚔ المعركة"),48);add(tv("تحدى الأصدقاء واجمع نقاط المعركة وارفع ترتيبك.",15),48);String[]b={"⚔ معركة فردية","👥 معركة فريق","🏆 ترتيب المتصدرين","🔥 معركة اليوم"};for(String s:b){Button q=btn(s);add(q,64);q.setOnClickListener(v->notice("ساحة المعركة جاهزة للتصميم وربط السيرفر."));}}
    void showEvents(){base();topBar("الأحداث",v->showHome());add(section("🏆 الأحداث والمكافآت"),48);add(tv("فعاليات يومية، هدايا، جوائز وترقيات داخل Dragon Chat.",15),48);String[]e={"🎁 المكافأة اليومية","👑 حدث VIP","💎 مضاعفة العملات","🔥 حدث نهاية الأسبوع"};for(String s:e){Button q=btn(s);add(q,64);q.setOnClickListener(v->notice("الحدث متاح كواجهة داخل التطبيق."));}}

    void showFriends(){base();topBar("الأصدقاء",v->showHome());add(section("👥 أصدقاؤك وأعضاء Dragon Chat"),48);try{Iterator<String>it=users.keys();boolean any=false;while(it.hasNext()){String em=it.next();if(em.equals(email))continue;JSONObject u=users.getJSONObject(em);ensureUserFields(u);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(8),dp(5),dp(8),dp(5));row.setBackground(round(CARD[themeIndex],dp(16)));row.addView(avatar(em,52),new LinearLayout.LayoutParams(dp(52),dp(52)));TextView z=tv(u.optString("name","عضو")+"\n"+u.optString("countryFlag","🇮🇶")+"  ID: "+u.optString("id"),13);row.addView(z,new LinearLayout.LayoutParams(0,dp(64),1));Button b=btn("دردشة");row.addView(b,new LinearLayout.LayoutParams(dp(82),dp(52)));addWrap(row);b.setOnClickListener(v->showChat(em));any=true;}if(!any)add(tv("لا يوجد أعضاء آخرون حالياً.",15),80);}catch(Exception ignored){}}
    void showChatList(){base();topBar("المجلس",v->showHome());add(section("💬 الرسائل والمحادثات"),48);try{Iterator<String>it=users.keys();while(it.hasNext()){String em=it.next();if(em.equals(email))continue;JSONObject u=users.getJSONObject(em);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.addView(avatar(em,55),new LinearLayout.LayoutParams(dp(55),dp(55)));row.addView(tv(u.optString("name","عضو")+"\nID: "+u.optString("id"),14),new LinearLayout.LayoutParams(0,dp(64),1));Button b=btn("فتح");row.addView(b,new LinearLayout.LayoutParams(dp(78),dp(52)));addWrap(row);b.setOnClickListener(v->showChat(em));}}catch(Exception ignored){}}
    void showChat(String target){try{JSONObject tu=users.getJSONObject(target);ensureUserFields(tu);LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(10),dp(8),dp(10),dp(10));page.setBackground(gradient());LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("‹");head.addView(back,new LinearLayout.LayoutParams(dp(52),dp(54)));head.addView(avatar(target,50),new LinearLayout.LayoutParams(dp(50),dp(50)));head.addView(tv(tu.optString("name","عضو")+"\n"+tu.optString("countryFlag","🇮🇶")+" ID: "+tu.optString("id"),14),new LinearLayout.LayoutParams(0,dp(58),1));Button pr=btn("ملف");head.addView(pr,new LinearLayout.LayoutParams(dp(70),dp(54)));page.addView(head);back.setOnClickListener(v->showChatList());pr.setOnClickListener(v->showProfile(target));ScrollView sc=new ScrollView(this);LinearLayout msgs=new LinearLayout(this);msgs.setOrientation(LinearLayout.VERTICAL);msgs.setPadding(dp(5),dp(8),dp(5),dp(8));String key=chatKey(email,target);JSONArray arr=chats.optJSONArray(key);if(arr==null)arr=new JSONArray();for(int i=0;i<arr.length();i++){JSONObject m=arr.optJSONObject(i);if(m==null)continue;boolean mine=email.equals(m.optString("from"));TextView bubble=tv(m.optString("text"),16);bubble.setPadding(dp(16),dp(12),dp(16),dp(12));bubble.setBackground(round(mine?Color.rgb(91,28,150):CARD[themeIndex],dp(18)));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams((int)(getResources().getDisplayMetrics().widthPixels*.78),dp(62));bp.gravity=mine?Gravity.LEFT:Gravity.RIGHT;bp.setMargins(0,dp(5),0,dp(5));msgs.addView(bubble,bp);}sc.addView(msgs);page.addView(sc,new LinearLayout.LayoutParams(-1,0,1));LinearLayout comp=new LinearLayout(this);EditText msg=input("اكتب رسالتك...",false);comp.addView(msg,new LinearLayout.LayoutParams(0,dp(58),1));Button send=btn("إرسال");comp.addView(send,new LinearLayout.LayoutParams(dp(82),dp(58)));page.addView(comp);send.setOnClickListener(v->{String s=msg.getText().toString().trim();if(s.isEmpty())return;try{JSONArray a=chats.optJSONArray(key);if(a==null)a=new JSONArray();JSONObject m=new JSONObject();m.put("from",email);m.put("text",s);m.put("time",System.currentTimeMillis());a.put(m);chats.put(key,a);save();showChat(target);}catch(Exception ignored){}});setContentView(page);applyBars();}catch(Exception e){notice("تعذر فتح الدردشة.");}}
    String chatKey(String a,String b){return a.compareTo(b)<0?a+"|"+b:b+"|"+a;}

    void showAdmin(){base();topBar("مركز الإدارة",v->showHome());try{JSONObject me=users.getJSONObject(email);addWrap(profileHero(me,email,false));add(tv("👑 صلاحيات المدير فقط: رفع مستوى العضو، العملات، المنصب وID المميز",13),45);Iterator<String>it=users.keys();while(it.hasNext()){String em=it.next();JSONObject u=users.getJSONObject(em);if(!"member".equals(u.optString("role")))continue;ensureUserFields(u);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(10),dp(8),dp(10),dp(8));card.setBackground(round(CARD[themeIndex],dp(18)));LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(avatar(em,58),new LinearLayout.LayoutParams(dp(58),dp(58)));r.addView(tv(u.optString("name","عضو")+"\nID: "+u.optString("id")+"\n💎 "+u.optInt("coins",0)+" • LV "+u.optInt("level",1),13),new LinearLayout.LayoutParams(0,dp(70),1));card.addView(r);LinearLayout bs=new LinearLayout(this);String[]labels={"عملات","رفع المستوى","سماح ID","ID مميز","الملف"};for(String s:labels){Button b=btn(s);bs.addView(b,new LinearLayout.LayoutParams(0,dp(50),1));if(s.equals("عملات"))b.setOnClickListener(v->giveDialog(em));else if(s.equals("رفع المستوى"))b.setOnClickListener(v->memberDialog(em));else if(s.equals("سماح ID"))b.setOnClickListener(v->toggleSpecialIdPermission(em));else if(s.equals("ID مميز"))b.setOnClickListener(v->specialIdDialog(em));else b.setOnClickListener(v->showProfile(em));}card.addView(bs);addWrap(card);}}catch(Exception ignored){}}
    void memberDialog(String target){try{JSONObject u=users.getJSONObject(target);int cur=u.optInt("level",1);String[]items=new String[10];for(int i=0;i<10;i++)items[i]=(i+1)+" - "+levelName(i+1);new AlertDialog.Builder(this).setTitle("رفع مستوى العضو").setSingleChoiceItems(items,Math.max(0,cur-1),(d,w)->{try{u.put("level",w+1);save();d.dismiss();notice("تم رفع المستوى إلى "+(w+1));showAdmin();}catch(Exception e){}}).setNegativeButton("إلغاء",null).show();}catch(Exception e){}}
    void giveDialog(String target){EditText a=input("عدد العملات",false);new AlertDialog.Builder(this).setTitle("إعطاء عملات للعضو").setMessage("ID: "+idOf(target)).setView(a).setPositiveButton("إعطاء",(d,w)->{try{int n=Integer.parseInt(a.getText().toString().trim());if(n<=0||n>1000000){notice("العدد غير صالح.");return;}JSONObject u=users.getJSONObject(target);u.put("coins",u.optInt("coins",0)+n);save();notice("تمت إضافة "+n+" عملة.");showAdmin();}catch(Exception e){notice("اكتب رقماً صحيحاً.");}}).setNegativeButton("إلغاء",null).show();}
    String idOf(String em){try{return users.getJSONObject(em).optString("id");}catch(Exception e){return "";}}
    boolean idExists(String wanted,String except){try{Iterator<String>it=users.keys();while(it.hasNext()){String em=it.next();if(em.equals(except))continue;JSONObject u=users.getJSONObject(em);if(wanted.equalsIgnoreCase(u.optString("id","")))return true;}}catch(Exception ignored){}return false;}
    void toggleSpecialIdPermission(String target){try{JSONObject u=users.getJSONObject(target);boolean n=!u.optBoolean("specialIdAllowed",false);u.put("specialIdAllowed",n);save();notice(n?"تم السماح للعضو باستخدام ID مميز.":"تم سحب صلاحية ID المميز.");showAdmin();}catch(Exception e){}}
    void specialIdDialog(String target){try{JSONObject u=users.getJSONObject(target);if(!u.optBoolean("specialIdAllowed",false)){notice("فعّل سماح ID أولاً.");return;}EditText x=input("مثال: 1000 أو VIP777",false);x.setText(u.optString("id",""));new AlertDialog.Builder(this).setTitle("تعيين ID مميز").setView(x).setPositiveButton("حفظ",(d,w)->{String wanted=x.getText().toString().trim();if(wanted.length()<3||wanted.length()>20||wanted.contains(" ")){notice("ID من 3 إلى 20 حرفاً أو رقماً وبدون مسافات.");return;}if(idExists(wanted,target)){notice("هذا ID مستخدم.");return;}try{u.put("id",wanted);save();notice("تم تعيين ID: "+wanted);showAdmin();}catch(Exception e){}}).setNegativeButton("إلغاء",null).show();}catch(Exception e){}}

    void themeDialog(){String[]items={"🟣 بنفسجي Dragon","🔵 أزرق ليلي","🟢 أخضر زمردي","🟠 ذهبي"};new AlertDialog.Builder(this).setTitle("اختيار لون التطبيق").setSingleChoiceItems(items,themeIndex,(d,w)->{themeIndex=w;prefs.edit().putInt("theme",w).apply();d.dismiss();applyBars();if(email.isEmpty())showLogin();else showHome();}).setNegativeButton("إلغاء",null).show();}
    void simple(String title,String body){base();topBar(title,v->showHome());add(tv(body,16),100);Button b=btn("رجوع");add(b,58);b.setOnClickListener(v->showHome());}
    void ensureAdmin(){try{if(!users.has("admin@drakon.com")){String[]h=hash("Admin123",null);JSONObject u=new JSONObject();u.put("email","admin@drakon.com");u.put("password_salt",h[0]);u.put("password_hash",h[1]);u.put("role","admin");u.put("coins",235680);u.put("level",99);u.put("active",true);u.put("id","100001");u.put("name","Drakon");u.put("bio","أسطورة هذا العالم");u.put("avatar","");u.put("countryFlag","🇮🇶");u.put("countryName","العراق");u.put("specialIdAllowed",true);u.put("online",true);users.put("admin@drakon.com",u);save();}else{ensureUserFields(users.getJSONObject("admin@drakon.com"));save();}}catch(Exception ignored){}}
    void ensureUserFields(JSONObject u)throws Exception{if(!u.has("id"))u.put("id",newUserId());if(!u.has("name"))u.put("name",u.optString("email","عضو"));if(!u.has("bio"))u.put("bio","");if(!u.has("specialIdAllowed"))u.put("specialIdAllowed",false);if(!u.has("coins"))u.put("coins",0);if(!u.has("level"))u.put("level",1);if(!u.has("avatar"))u.put("avatar","");if(!u.has("countryFlag"))u.put("countryFlag","🇮🇶");if(!u.has("countryName"))u.put("countryName","العراق");if(!u.has("online"))u.put("online",true);}
    String newUserId(){long n=System.currentTimeMillis()%1000000000L;int r=new SecureRandom().nextInt(900)+100;return "DRK-"+n+"-"+r;}
    JSONObject loadObject(String key){try{return new JSONObject(prefs.getString(key,"{}"));}catch(Exception e){return new JSONObject();}}
    void save(){prefs.edit().putString("users",users.toString()).putString("chats",chats.toString()).apply();}
    void notice(String s){new AlertDialog.Builder(this).setTitle("Dragon Chat").setMessage(s).setPositiveButton("حسناً",null).show();}
    String[] hash(String password,String salt)throws Exception{if(salt==null){byte[]b=new byte[16];new SecureRandom().nextBytes(b);salt=android.util.Base64.encodeToString(b,android.util.Base64.NO_WRAP);}PBEKeySpec spec=new PBEKeySpec(password.toCharArray(),salt.getBytes(StandardCharsets.UTF_8),120000,256);byte[]d=SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(spec).getEncoded();return new String[]{salt,android.util.Base64.encodeToString(d,android.util.Base64.NO_WRAP)};}
    boolean verify(String p,String s,String d)throws Exception{return MessageDigest.isEqual(hash(p,s)[1].getBytes(StandardCharsets.UTF_8),d.getBytes(StandardCharsets.UTF_8));}
}
